[rank: 0] Global seed set to 0
Traceback (most recent call last):
  File "/projects/dali/spack/var/spack/environments/dali/.spack-env/view/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
  File "/home/yichia3/torchgeo/torchgeo/trainers/segmentation.py", line 171, in __init__
    self.config_task()
  File "/home/yichia3/torchgeo/torchgeo/trainers/segmentation.py", line 95, in config_task
    state_dict = get_weight(weights).get_state_dict(progress=True)
  File "/home/yichia3/torchgeo/torchgeo/models/api.py", line 79, in get_weight
    return eval(name)
  File "<string>", line 1
    /projects/dali/data/pretrained_weights/ssl4eo-l-etm-sr-mocov2-resnet18/torchgeo.datamodules.ssl4eollmdbdatamodule_torchgeo.trainers.mocotask/ssl4eo-l-etm-sr-mocov2-resnet50_backbone.ckpt
    ^
SyntaxError: invalid syntax

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/yichia3/torchgeo/train.py", line 156, in <module>
    main(conf)
  File "/home/yichia3/torchgeo/train.py", line 92, in main
    task: LightningModule = instantiate(conf.module)
  File "/projects/dali/spack/var/spack/environments/dali/.spack-env/view/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
  File "/projects/dali/spack/var/spack/environments/dali/.spack-env/view/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 347, in instantiate_node
    return _call_target(_target_, partial, args, kwargs, full_key)
  File "/projects/dali/spack/var/spack/environments/dali/.spack-env/view/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 97, in _call_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error in call to target 'torchgeo.trainers.segmentation.SemanticSegmentationTask':
SyntaxError('invalid syntax', ('<string>', 1, 1, '/projects/dali/data/pretrained_weights/ssl4eo-l-etm-sr-mocov2-resnet18/torchgeo.datamodules.ssl4eollmdbdatamodule_torchgeo.trainers.mocotask/ssl4eo-l-etm-sr-mocov2-resnet50_backbone.ckpt', 1, 2))
full_key: module
[rank: 0] Global seed set to 0
Traceback (most recent call last):
  File "/projects/dali/spack/var/spack/environments/dali/.spack-env/view/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
  File "/home/yichia3/torchgeo/torchgeo/trainers/segmentation.py", line 171, in __init__
    self.config_task()
  File "/home/yichia3/torchgeo/torchgeo/trainers/segmentation.py", line 95, in config_task
    state_dict = get_weight(weights).get_state_dict(progress=True)
  File "/home/yichia3/torchgeo/torchgeo/models/api.py", line 79, in get_weight
    return eval(name)
  File "<string>", line 1
    /projects/dali/data/pretrained_weights/ssl4eo-l-etm-sr-mocov2-resnet18/torchgeo.datamodules.ssl4eollmdbdatamodule_torchgeo.trainers.mocotask/ssl4eo-l-etm-sr-mocov2-resnet50_backbone.ckpt
    ^
SyntaxError: invalid syntax

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/yichia3/torchgeo/train.py", line 156, in <module>
    main(conf)
  File "/home/yichia3/torchgeo/train.py", line 92, in main
    task: LightningModule = instantiate(conf.module)
  File "/projects/dali/spack/var/spack/environments/dali/.spack-env/view/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
  File "/projects/dali/spack/var/spack/environments/dali/.spack-env/view/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 347, in instantiate_node
    return _call_target(_target_, partial, args, kwargs, full_key)
  File "/projects/dali/spack/var/spack/environments/dali/.spack-env/view/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 97, in _call_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error in call to target 'torchgeo.trainers.segmentation.SemanticSegmentationTask':
SyntaxError('invalid syntax', ('<string>', 1, 1, '/projects/dali/data/pretrained_weights/ssl4eo-l-etm-sr-mocov2-resnet18/torchgeo.datamodules.ssl4eollmdbdatamodule_torchgeo.trainers.mocotask/ssl4eo-l-etm-sr-mocov2-resnet50_backbone.ckpt', 1, 2))
full_key: module
[rank: 0] Global seed set to 0
Traceback (most recent call last):
  File "/projects/dali/spack/var/spack/environments/dali/.spack-env/view/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
  File "/home/yichia3/torchgeo/torchgeo/trainers/segmentation.py", line 171, in __init__
    self.config_task()
  File "/home/yichia3/torchgeo/torchgeo/trainers/segmentation.py", line 95, in config_task
    state_dict = get_weight(weights).get_state_dict(progress=True)
  File "/home/yichia3/torchgeo/torchgeo/models/api.py", line 79, in get_weight
    return eval(name)
  File "<string>", line 1
    /projects/dali/data/pretrained_weights/ssl4eo-l-etm-sr-mocov2-resnet18/torchgeo.datamodules.ssl4eollmdbdatamodule_torchgeo.trainers.mocotask/ssl4eo-l-etm-sr-mocov2-resnet50_backbone.ckpt
    ^
SyntaxError: invalid syntax

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/yichia3/torchgeo/train.py", line 156, in <module>
    main(conf)
  File "/home/yichia3/torchgeo/train.py", line 92, in main
    task: LightningModule = instantiate(conf.module)
  File "/projects/dali/spack/var/spack/environments/dali/.spack-env/view/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
  File "/projects/dali/spack/var/spack/environments/dali/.spack-env/view/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 347, in instantiate_node
    return _call_target(_target_, partial, args, kwargs, full_key)
  File "/projects/dali/spack/var/spack/environments/dali/.spack-env/view/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 97, in _call_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error in call to target 'torchgeo.trainers.segmentation.SemanticSegmentationTask':
SyntaxError('invalid syntax', ('<string>', 1, 1, '/projects/dali/data/pretrained_weights/ssl4eo-l-etm-sr-mocov2-resnet18/torchgeo.datamodules.ssl4eollmdbdatamodule_torchgeo.trainers.mocotask/ssl4eo-l-etm-sr-mocov2-resnet50_backbone.ckpt', 1, 2))
full_key: module
[rank: 0] Global seed set to 0
Traceback (most recent call last):
  File "/projects/dali/spack/var/spack/environments/dali/.spack-env/view/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
  File "/home/yichia3/torchgeo/torchgeo/trainers/segmentation.py", line 171, in __init__
    self.config_task()
  File "/home/yichia3/torchgeo/torchgeo/trainers/segmentation.py", line 95, in config_task
    state_dict = get_weight(weights).get_state_dict(progress=True)
  File "/home/yichia3/torchgeo/torchgeo/models/api.py", line 79, in get_weight
    return eval(name)
  File "<string>", line 1
    /projects/dali/data/pretrained_weights/ssl4eo-l-etm-sr-mocov2-resnet18/torchgeo.datamodules.ssl4eollmdbdatamodule_torchgeo.trainers.mocotask/ssl4eo-l-etm-sr-mocov2-resnet50_backbone.ckpt
    ^
SyntaxError: invalid syntax

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/yichia3/torchgeo/train.py", line 156, in <module>
    main(conf)
  File "/home/yichia3/torchgeo/train.py", line 92, in main
    task: LightningModule = instantiate(conf.module)
  File "/projects/dali/spack/var/spack/environments/dali/.spack-env/view/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
  File "/projects/dali/spack/var/spack/environments/dali/.spack-env/view/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 347, in instantiate_node
    return _call_target(_target_, partial, args, kwargs, full_key)
  File "/projects/dali/spack/var/spack/environments/dali/.spack-env/view/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 97, in _call_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error in call to target 'torchgeo.trainers.segmentation.SemanticSegmentationTask':
SyntaxError('invalid syntax', ('<string>', 1, 1, '/projects/dali/data/pretrained_weights/ssl4eo-l-etm-sr-mocov2-resnet18/torchgeo.datamodules.ssl4eollmdbdatamodule_torchgeo.trainers.mocotask/ssl4eo-l-etm-sr-mocov2-resnet50_backbone.ckpt', 1, 2))
full_key: module
[rank: 0] Global seed set to 0
Traceback (most recent call last):
  File "/projects/dali/spack/var/spack/environments/dali/.spack-env/view/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
  File "/home/yichia3/torchgeo/torchgeo/trainers/segmentation.py", line 171, in __init__
    self.config_task()
  File "/home/yichia3/torchgeo/torchgeo/trainers/segmentation.py", line 95, in config_task
    state_dict = get_weight(weights).get_state_dict(progress=True)
  File "/home/yichia3/torchgeo/torchgeo/models/api.py", line 79, in get_weight
    return eval(name)
  File "<string>", line 1
    /projects/dali/data/pretrained_weights/ssl4eo-l-etm-sr-mocov2-resnet18/torchgeo.datamodules.ssl4eollmdbdatamodule_torchgeo.trainers.mocotask/ssl4eo-l-etm-sr-mocov2-resnet50_backbone.ckpt
    ^
SyntaxError: invalid syntax

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/yichia3/torchgeo/train.py", line 156, in <module>
    main(conf)
  File "/home/yichia3/torchgeo/train.py", line 92, in main
    task: LightningModule = instantiate(conf.module)
  File "/projects/dali/spack/var/spack/environments/dali/.spack-env/view/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
  File "/projects/dali/spack/var/spack/environments/dali/.spack-env/view/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 347, in instantiate_node
    return _call_target(_target_, partial, args, kwargs, full_key)
  File "/projects/dali/spack/var/spack/environments/dali/.spack-env/view/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 97, in _call_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error in call to target 'torchgeo.trainers.segmentation.SemanticSegmentationTask':
SyntaxError('invalid syntax', ('<string>', 1, 1, '/projects/dali/data/pretrained_weights/ssl4eo-l-etm-sr-mocov2-resnet18/torchgeo.datamodules.ssl4eollmdbdatamodule_torchgeo.trainers.mocotask/ssl4eo-l-etm-sr-mocov2-resnet50_backbone.ckpt', 1, 2))
full_key: module
[rank: 0] Global seed set to 0
Traceback (most recent call last):
  File "/projects/dali/spack/var/spack/environments/dali/.spack-env/view/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
  File "/home/yichia3/torchgeo/torchgeo/trainers/segmentation.py", line 171, in __init__
    self.config_task()
  File "/home/yichia3/torchgeo/torchgeo/trainers/segmentation.py", line 95, in config_task
    state_dict = get_weight(weights).get_state_dict(progress=True)
  File "/home/yichia3/torchgeo/torchgeo/models/api.py", line 79, in get_weight
    return eval(name)
  File "<string>", line 1
    /projects/dali/data/pretrained_weights/ssl4eo-l-etm-sr-mocov2-resnet18/torchgeo.datamodules.ssl4eollmdbdatamodule_torchgeo.trainers.mocotask/ssl4eo-l-etm-sr-mocov2-resnet50_backbone.ckpt
    ^
SyntaxError: invalid syntax

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/yichia3/torchgeo/train.py", line 156, in <module>
    main(conf)
  File "/home/yichia3/torchgeo/train.py", line 92, in main
    task: LightningModule = instantiate(conf.module)
  File "/projects/dali/spack/var/spack/environments/dali/.spack-env/view/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
  File "/projects/dali/spack/var/spack/environments/dali/.spack-env/view/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 347, in instantiate_node
    return _call_target(_target_, partial, args, kwargs, full_key)
  File "/projects/dali/spack/var/spack/environments/dali/.spack-env/view/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 97, in _call_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error in call to target 'torchgeo.trainers.segmentation.SemanticSegmentationTask':
SyntaxError('invalid syntax', ('<string>', 1, 1, '/projects/dali/data/pretrained_weights/ssl4eo-l-etm-sr-mocov2-resnet18/torchgeo.datamodules.ssl4eollmdbdatamodule_torchgeo.trainers.mocotask/ssl4eo-l-etm-sr-mocov2-resnet50_backbone.ckpt', 1, 2))
full_key: module
slurmstepd: error: *** JOB 8969045 ON ccc0284 CANCELLED AT 2023-06-06T16:50:06 ***
